GET https://autumn-delicate-wilderness.glitch.me/v1/content/skills

###
DELETE https://autumn-delicate-wilderness.glitch.me/v1/content/skills/265

###
POST https://autumn-delicate-wilderness.glitch.me/v1/auth/login
Content-Type: application/json

{
  "email": "asus@email.com",
  "password": "verysecret125"
}

###
POST https://autumn-delicate-wilderness.glitch.me/v1/content/skills
Content-Type: application/json

{
  "title": "test2",
   "description": "Testing2"
}